obj-$(CONFIG_PAMIR_AI_SAM_MODULE) += pamir-ai-sam.o

pamir-ai-sam-y := pamir-sam-main.o pamir-sam-protocol.o pamir-sam-input.o \
                  pamir-sam-led.o pamir-sam-power.o pamir-sam-display.o \
                  pamir-sam-debug.o pamir-sam-system.o pamir-sam-chardev.o 